name: BattlecraftServer
main: org.battlecraft.piesrgr8.BattlecraftServer
version: 1.5, 1.9
author: Piesrgr8
description: This plugin is for the Battlecraft Server.

commands:
  armor:
    description: Grants the player armor for protection.
  ban:
    description: Ban players.
  bc:
    description: The main command for the plugin.
  clear:
    description: Clear your inventory.
  death:
    description: Kill yourself.
  enderchest:
    description: Open players inventory.
    aliases: [ec,echest,enderc]
  fakej:
    description: Fake a join!
  fakel:
    description: Fake a leave!
  fakeb:
    description: Fake a ban!
  fakek:
    description: Fake a kick!
  forceop:
    description: Fake an op!
  g0:
    description: Set gamemode to Survival.
    aliases: [gms,gs]
  g1:
    description: Set gamemode to Creative.
    aliases: [gmc,gc]
  g2:
    description: Set gamemode to Adventure.
    aliases: [gma,ga]
  g3:
    description: Set gamemode to Spectator.
    aliases: [gmsp,gsp]
  heal:
    description: Heal yourself.
  hub:
    description: Spawn in the hub.
  information:
    description: Shows what you can do!
  invsee:
    description: Open up a players inventory.
  issue:
    description: Send an issue if you spot any problems.
  kick:
    description: Kick players.
  kit:
    description: Gives kits to players.
  kiosk:
    description: Opens a menu for recently bought items.
  maintenance:
    description: Start maintenance.
  menu:
    description: Shows the menu for teleporting.
  mute:
    description: Mute players.
  nickname:
    description: Set a nickname for yourself.
  particle:
    description: Get particles.
  player:
    description: Add or remove a player from the list.
  poll:
    description: Vote for an ongoing poll.
  report:
    description: Report a player for breaking rules.
  restart:
    description: Restart the server.
  reload:
    description: Reload the server.
  save:
    description: Save worlds.
  scan:
    description: Scan for entities.
  send:
    description: Send different messages.
  sethub:
    description: Set the hub!
  setwarp:
    description: Set the warp!
  spam:
    description: Spam a certain message.
  spawn:
    description: Spawn in the hub.
  spawner:
    description: Spawn things.
  staff:
    description: This is a command for the staff team!
  stats:
    description: Check out your stats!
  sword:
    description: Gives a sword to defend a player!
  tell:
    description: Tell players a secret or something.
  test:
    description: Piesrgr8 tests methods with this command!
  tp:
    description: Teleportation at its finest!
  tphere:
    description: Teleportation at its finest!
  unmute:
    description: Unmute players.
  vs:
    description: Vanish from players.
  website:
    description: Get the URL for the website!
  warp:
    description: Teleport to a location!
  world:
    description: Get the current world that you are in!

permissions:
    bc.*:
        description: Gives all permissions to a player.
        children:
            bc.armor: true
            bc.ban: true
            bc.fakek: true
            bc.fakeb: true
            bc.fakej: true
            bc.fakel: true
            bc.full: true
            bc.gamemode0: true
            bc.gamemode1: true
            bc.gamemode2: true
            bc.gamemode3: true
            bc.helpbypass: true
            bc.invsee: true
            bc.kick: true
            bc.main: true
            bc.mutebypass: true
            bc.mute: true
            bc.nick: true
            bc.placedblocked: true
            bc.player: true
            bc.rank: true
            bc.save: true
            bc.silentjoin: true
            bc.silentquit: true
            bc.test: true
            bc.unmute: true
            bc.vanish: true
    bc.kit.*:
        description: Gives all kits to a player.
        children:
            bc.kit: true
            bc.kit.starter: true
            bc.kit.vip: true
            bc.kit.vip1: true
            bc.kit.vip2: true
            bc.kit.master: true
            bc.kit.premium: true
            bc.kit.staff: true
            bc.kit.yt: true
    bc.armor:
        description: Grants the player armor for protection.
    bc.ban:
        description: Ban players.
    bc.clear:
        description: Clear inventory.
    bc.fakek:
        description: Fake a kick!
    bc.fakeb:
        description: Fake a ban!
    bc.fakej:
        description: Fake a join!
    bc.fakel:
        description: Fake a leave!
    bc.full:
        description: Join the server when it is currently full!
    bc.gamemode0:
        description: Set gamemode to Survival.
    bc.gamemode1:
        description: Set gamemode to Creative.
    bc.gamemode2:
        description: Set gamemode to Adventure.
    bc.gamemode3:
        description: Set gamemode to Spectator.
    bc.helpbypass:
        description: Bypasses the help message.
    bc.invsee:
        description: Open a players inventory.
    bc.kick:
        description: Kick players.
    bc.kit:
        description: The main command for kits.
    bc.kit.starter:
        description: Gives starter kit!
    bc.kit.vip:
        description: Gives vip kit!
    bc.kit.vip1:
        description: Gives vip+ kit!
    bc.kit.vip2:
        description: Gives +vip+ kit!
    bc.kit.master:
        description: Gives master kit!
    bc.kit.premium:
        description: Gives premium kit!
    bc.kit.staff:
        description: Gives staff kit!
    bc.kit.yt:
        description: Gives yt kit!
    bc.main:
        description: The main plugin permission.
    bc.mutebypass:
        description: Bypass the mute command.
    bc.mute:
        description: Mute players.
    bc.nick:
        description: Set a nickname for yourself.
    bc.placeblocked:
        description: Permission to place a blocked block.
    bc.player:
        description: Add or remove a player from a list.
    bc.prefix.owner:
        description: For chat purposes.
    bc.prefix.cowner:
        description: For chat purposes.
    bc.prefix.admin:
        description: For chat purposes.
    bc.prefix.dev:
        description: For chat purposes.
    bc.prefix.mod:
        description: For chat purposes.
    bc.prefix.helper:
        description: For chat purposes.
    bc.prefix.builder:
        description: For chat purposes.
    bc.rank:
        description: Set ranks for different players!
    bc.save:
        description: Save all worlds.
    bc.sethub:
        description: Set the hub.
    bc.setwarp:
        description: Set the warp.
    bc.silentjoin:
        description: Silently sneak into the server.
    bc.silentquit:
        description: Silently quit the server.
    bc.staff:
        description: This is a command for the staff team!
    bc.test:
        description: Testing a method.
    bc.teleport:
        description: Teleportation at its finest!
    bc.unmute:
        description: Unmute players.
    bc.vanish:
        description: Vanish from players.